### PR TITLE
Update SlidingMenuDemo/src/grimbo/android/demo/slidingmenu/SlideAnimatio...

### PR DESCRIPTION
**Pull request by alessandro-lac**
...nThenCallLayout.java

### CODE REVIEW

**Comment by alessandro-lac** [comment]
Solved the flicker issue :)

**Comment by gitgrimbo** [comment]
Thanks, I'll take a look!

**Comment by ahmedeltaher** [comment]
i need that code to make slide from right to left , how can  do it , thanks advance.

**Comment by pre2612** [comment]
Hi,

I am using your code to Display drawers but I want to use 2 drawers left and right on click of 2 separate buttons.
Could you please tell me how to implement this using your code?

i am a beginner developer need help creating right side drawer.

Thanks a  lot for your help!

**Pull request merged**
